2014/06/07 18:31:33 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1049] Unknown database 'testdrive'' in C:\xampp\htdocs\framework\yii\framework\db\CDbConnection.php:382
Stack trace:
#0 C:\xampp\htdocs\framework\yii\framework\db\CDbConnection.php(330): CDbConnection->open()
#1 C:\xampp\htdocs\framework\yii\framework\db\CDbConnection.php(308): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\framework\yii\framework\base\CModule.php(387): CDbConnection->init()
#3 C:\xampp\htdocs\framework\yii\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\htdocs\framework\yii\framework\gii\generators\model\ModelCode.php(60): CModule->__get('db')
#5 C:\xampp\htdocs\framework\yii\framework\web\CFormModel.php(39): ModelCode->init()
#6 C:\xampp\htdocs\framework\yii\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\xampp\htdocs\framework\yii\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\xampp\htdocs\framework\yii\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\xampp\htdocs\framework\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\framework\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\framework\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\framework\yii\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\htdocs\framework\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 C:\xampp\htdocs\framework\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#15 C:\xampp\htdocs\framework\yiiframework\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/framework/yiiframework/index.php/gii/model/index
HTTP_REFERER=http://localhost/framework/yiiframework/index.php/gii/default/index
---
2014/06/07 18:32:24 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1049] Unknown database 'testdrive'' in C:\xampp\htdocs\framework\yii\framework\db\CDbConnection.php:382
Stack trace:
#0 C:\xampp\htdocs\framework\yii\framework\db\CDbConnection.php(330): CDbConnection->open()
#1 C:\xampp\htdocs\framework\yii\framework\db\CDbConnection.php(308): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\framework\yii\framework\base\CModule.php(387): CDbConnection->init()
#3 C:\xampp\htdocs\framework\yii\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\htdocs\framework\yii\framework\gii\generators\model\ModelCode.php(60): CModule->__get('db')
#5 C:\xampp\htdocs\framework\yii\framework\web\CFormModel.php(39): ModelCode->init()
#6 C:\xampp\htdocs\framework\yii\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\xampp\htdocs\framework\yii\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\xampp\htdocs\framework\yii\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\xampp\htdocs\framework\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\framework\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\framework\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\framework\yii\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\htdocs\framework\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 C:\xampp\htdocs\framework\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#15 C:\xampp\htdocs\framework\yiiframework\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/framework/yiiframework/index.php/gii/model/index
HTTP_REFERER=http://localhost/framework/yiiframework/index.php/gii/default/index
---
2014/06/07 18:33:07 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1049] Unknown database 'testdrive'' in C:\xampp\htdocs\framework\yii\framework\db\CDbConnection.php:382
Stack trace:
#0 C:\xampp\htdocs\framework\yii\framework\db\CDbConnection.php(330): CDbConnection->open()
#1 C:\xampp\htdocs\framework\yii\framework\db\CDbConnection.php(308): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\framework\yii\framework\base\CModule.php(387): CDbConnection->init()
#3 C:\xampp\htdocs\framework\yii\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\htdocs\framework\yii\framework\gii\generators\model\ModelCode.php(60): CModule->__get('db')
#5 C:\xampp\htdocs\framework\yii\framework\web\CFormModel.php(39): ModelCode->init()
#6 C:\xampp\htdocs\framework\yii\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\xampp\htdocs\framework\yii\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\xampp\htdocs\framework\yii\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\xampp\htdocs\framework\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\framework\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\framework\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\framework\yii\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\htdocs\framework\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 C:\xampp\htdocs\framework\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#15 C:\xampp\htdocs\framework\yiiframework\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/framework/yiiframework/index.php/gii/model/index
HTTP_REFERER=http://localhost/framework/yiiframework/index.php/gii/default/index
---
2014/06/07 18:40:26 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "users".' in C:\xampp\htdocs\framework\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\framework\yii\framework\web\CController.php(270): CController->missingAction('users')
#1 C:\xampp\htdocs\framework\yii\framework\web\CWebApplication.php(282): CController->run('users')
#2 C:\xampp\htdocs\framework\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/users')
#3 C:\xampp\htdocs\framework\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\framework\yiiframework\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/framework/yiiframework/index.php/site/users
---
2014/06/07 18:40:32 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "user".' in C:\xampp\htdocs\framework\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\framework\yii\framework\web\CController.php(270): CController->missingAction('user')
#1 C:\xampp\htdocs\framework\yii\framework\web\CWebApplication.php(282): CController->run('user')
#2 C:\xampp\htdocs\framework\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/user')
#3 C:\xampp\htdocs\framework\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\framework\yiiframework\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/framework/yiiframework/index.php/site/user
---
2014/06/07 19:28:28 [error] [php] include(Employee.php): failed to open stream: No such file or directory (C:\xampp\htdocs\framework\yii\framework\YiiBase.php:427)
Stack trace:
#0 C:\xampp\htdocs\framework\yiiframework\protected\components\UserIdentity.php(38): spl_autoload_call()
#1 C:\xampp\htdocs\framework\yiiframework\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#2 C:\xampp\htdocs\framework\yii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate()
#3 C:\xampp\htdocs\framework\yii\framework\validators\CValidator.php(213): CInlineValidator->validateAttribute()
#4 C:\xampp\htdocs\framework\yii\framework\base\CModel.php(159): CInlineValidator->validate()
#5 C:\xampp\htdocs\framework\yiiframework\protected\controllers\SiteController.php(91): LoginForm->validate()
#6 C:\xampp\htdocs\framework\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#7 C:\xampp\htdocs\framework\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#8 C:\xampp\htdocs\framework\yii\framework\web\CController.php(286): SiteController->runAction()
#9 C:\xampp\htdocs\framework\yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#10 C:\xampp\htdocs\framework\yii\framework\web\CWebApplication.php(282): SiteController->run()
#11 C:\xampp\htdocs\framework\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#12 C:\xampp\htdocs\framework\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#13 C:\xampp\htdocs\framework\yiiframework\index.php(13): CWebApplication->run()
REQUEST_URI=/framework/yiiframework/index.php/site/login
in C:\xampp\htdocs\framework\yiiframework\protected\components\UserIdentity.php (38)
in C:\xampp\htdocs\framework\yiiframework\protected\models\LoginForm.php (52)
in C:\xampp\htdocs\framework\yiiframework\protected\controllers\SiteController.php (91)
2014/06/07 19:29:28 [error] [exception.CDbException] exception 'CDbException' with message 'Table "users" does not have a column named "E_EMAIL".' in C:\xampp\htdocs\framework\yii\framework\db\schema\CDbCommandBuilder.php:694
Stack trace:
#0 C:\xampp\htdocs\framework\yii\framework\db\ar\CActiveRecord.php(1518): CDbCommandBuilder->createColumnCriteria(Object(CMysqlTableSchema), Array, '', Array, '`t`.')
#1 C:\xampp\htdocs\framework\yiiframework\protected\components\UserIdentity.php(37): CActiveRecord->findByAttributes(Array)
#2 C:\xampp\htdocs\framework\yiiframework\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#3 C:\xampp\htdocs\framework\yii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#4 C:\xampp\htdocs\framework\yii\framework\validators\CValidator.php(213): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#5 C:\xampp\htdocs\framework\yii\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#6 C:\xampp\htdocs\framework\yiiframework\protected\controllers\SiteController.php(91): CModel->validate()
#7 C:\xampp\htdocs\framework\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#8 C:\xampp\htdocs\framework\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\xampp\htdocs\framework\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 C:\xampp\htdocs\framework\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\framework\yii\framework\web\CWebApplication.php(282): CController->run('login')
#12 C:\xampp\htdocs\framework\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#13 C:\xampp\htdocs\framework\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#14 C:\xampp\htdocs\framework\yiiframework\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/framework/yiiframework/index.php/site/login
HTTP_REFERER=http://localhost/framework/yiiframework/index.php/site/login
---
2014/06/07 19:30:38 [error] [exception.CException] exception 'CException' with message 'Property "Users.E_PASSWORD" is not defined.' in C:\xampp\htdocs\framework\yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\framework\yii\framework\db\ar\CActiveRecord.php(145): CComponent->__get('E_PASSWORD')
#1 C:\xampp\htdocs\framework\yiiframework\protected\components\UserIdentity.php(41): CActiveRecord->__get('E_PASSWORD')
#2 C:\xampp\htdocs\framework\yiiframework\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#3 C:\xampp\htdocs\framework\yii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#4 C:\xampp\htdocs\framework\yii\framework\validators\CValidator.php(213): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#5 C:\xampp\htdocs\framework\yii\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#6 C:\xampp\htdocs\framework\yiiframework\protected\controllers\SiteController.php(91): CModel->validate()
#7 C:\xampp\htdocs\framework\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#8 C:\xampp\htdocs\framework\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\xampp\htdocs\framework\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 C:\xampp\htdocs\framework\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\framework\yii\framework\web\CWebApplication.php(282): CController->run('login')
#12 C:\xampp\htdocs\framework\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#13 C:\xampp\htdocs\framework\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#14 C:\xampp\htdocs\framework\yiiframework\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/framework/yiiframework/index.php/site/login
HTTP_REFERER=http://localhost/framework/yiiframework/index.php/site/login
---
2014/06/07 19:33:20 [error] [exception.CException] exception 'CException' with message 'Property "Users.E_STATUS" is not defined.' in C:\xampp\htdocs\framework\yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\framework\yii\framework\db\ar\CActiveRecord.php(145): CComponent->__get('E_STATUS')
#1 C:\xampp\htdocs\framework\yii\framework\base\CModel.php(596): CActiveRecord->__get('E_STATUS')
#2 C:\xampp\htdocs\framework\yiiframework\protected\components\UserIdentity.php(46): CModel->offsetGet('E_STATUS')
#3 C:\xampp\htdocs\framework\yiiframework\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#4 C:\xampp\htdocs\framework\yii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#5 C:\xampp\htdocs\framework\yii\framework\validators\CValidator.php(213): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#6 C:\xampp\htdocs\framework\yii\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#7 C:\xampp\htdocs\framework\yiiframework\protected\controllers\SiteController.php(91): CModel->validate()
#8 C:\xampp\htdocs\framework\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#9 C:\xampp\htdocs\framework\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\framework\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\framework\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\framework\yii\framework\web\CWebApplication.php(282): CController->run('login')
#13 C:\xampp\htdocs\framework\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#14 C:\xampp\htdocs\framework\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#15 C:\xampp\htdocs\framework\yiiframework\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/framework/yiiframework/index.php/site/login
HTTP_REFERER=http://localhost/framework/yiiframework/index.php/site/login
---
2014/06/07 19:33:25 [error] [exception.CException] exception 'CException' with message 'Property "Users.E_STATUS" is not defined.' in C:\xampp\htdocs\framework\yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\framework\yii\framework\db\ar\CActiveRecord.php(145): CComponent->__get('E_STATUS')
#1 C:\xampp\htdocs\framework\yii\framework\base\CModel.php(596): CActiveRecord->__get('E_STATUS')
#2 C:\xampp\htdocs\framework\yiiframework\protected\components\UserIdentity.php(46): CModel->offsetGet('E_STATUS')
#3 C:\xampp\htdocs\framework\yiiframework\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#4 C:\xampp\htdocs\framework\yii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#5 C:\xampp\htdocs\framework\yii\framework\validators\CValidator.php(213): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#6 C:\xampp\htdocs\framework\yii\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#7 C:\xampp\htdocs\framework\yiiframework\protected\controllers\SiteController.php(91): CModel->validate()
#8 C:\xampp\htdocs\framework\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#9 C:\xampp\htdocs\framework\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\framework\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\framework\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\framework\yii\framework\web\CWebApplication.php(282): CController->run('login')
#13 C:\xampp\htdocs\framework\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#14 C:\xampp\htdocs\framework\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#15 C:\xampp\htdocs\framework\yiiframework\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/framework/yiiframework/index.php/site/login
HTTP_REFERER=http://localhost/framework/yiiframework/index.php/site/login
---
2014/06/07 19:34:15 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "page_after_login".' in C:\xampp\htdocs\framework\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\framework\yii\framework\web\CController.php(270): CController->missingAction('page_after_logi...')
#1 C:\xampp\htdocs\framework\yii\framework\web\CWebApplication.php(282): CController->run('page_after_logi...')
#2 C:\xampp\htdocs\framework\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/page_after...')
#3 C:\xampp\htdocs\framework\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\framework\yiiframework\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/framework/yiiframework/index.php/site/page_after_login
HTTP_REFERER=http://localhost/framework/yiiframework/index.php/site/login
---
2014/06/07 19:34:45 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "page_after_login".' in C:\xampp\htdocs\framework\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\framework\yii\framework\web\CController.php(270): CController->missingAction('page_after_logi...')
#1 C:\xampp\htdocs\framework\yii\framework\web\CWebApplication.php(282): CController->run('page_after_logi...')
#2 C:\xampp\htdocs\framework\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/page_after...')
#3 C:\xampp\htdocs\framework\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\framework\yiiframework\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/framework/yiiframework/index.php/site/page_after_login
HTTP_REFERER=http://localhost/framework/yiiframework/index.php/site/login
---
2014/06/08 16:38:14 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "page_after_login".' in C:\xampp\htdocs\framework\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\framework\yii\framework\web\CController.php(270): CController->missingAction('page_after_logi...')
#1 C:\xampp\htdocs\framework\yii\framework\web\CWebApplication.php(282): CController->run('page_after_logi...')
#2 C:\xampp\htdocs\framework\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/page_after...')
#3 C:\xampp\htdocs\framework\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\framework\yiiframework\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/framework/yiiframework/index.php/site/page_after_login
HTTP_REFERER=http://localhost/framework/yiiframework/index.php/site/login
---
2014/06/08 16:38:49 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "page_after_login".' in C:\xampp\htdocs\framework\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\framework\yii\framework\web\CController.php(270): CController->missingAction('page_after_logi...')
#1 C:\xampp\htdocs\framework\yii\framework\web\CWebApplication.php(282): CController->run('page_after_logi...')
#2 C:\xampp\htdocs\framework\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/page_after...')
#3 C:\xampp\htdocs\framework\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\framework\yiiframework\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/framework/yiiframework/index.php/site/page_after_login
HTTP_REFERER=http://localhost/framework/yiiframework/index.php/site/login
---
2014/06/08 16:39:04 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "home".' in C:\xampp\htdocs\framework\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\framework\yii\framework\web\CController.php(270): CController->missingAction('home')
#1 C:\xampp\htdocs\framework\yii\framework\web\CWebApplication.php(282): CController->run('home')
#2 C:\xampp\htdocs\framework\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/home')
#3 C:\xampp\htdocs\framework\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\framework\yiiframework\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/framework/yiiframework/index.php/site/home
HTTP_REFERER=http://localhost/framework/yiiframework/index.php/site/login
---
2014/06/08 16:42:19 [error] [exception.CException] exception 'CException' with message 'Property "CWebUser.email" is not defined.' in C:\xampp\htdocs\framework\yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\framework\yii\framework\web\auth\CWebUser.php(146): CComponent->__get('email')
#1 C:\xampp\htdocs\framework\yiiframework\protected\views\layouts\main.php(37): CWebUser->__get('email')
#2 C:\xampp\htdocs\framework\yii\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#3 C:\xampp\htdocs\framework\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#4 C:\xampp\htdocs\framework\yii\framework\web\widgets\CContentDecorator.php(76): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#5 C:\xampp\htdocs\framework\yii\framework\web\widgets\CContentDecorator.php(54): CContentDecorator->decorate('<div id="conten...')
#6 C:\xampp\htdocs\framework\yii\framework\web\widgets\COutputProcessor.php(44): CContentDecorator->processOutput('<div id="conten...')
#7 C:\xampp\htdocs\framework\yii\framework\web\CBaseController.php(206): COutputProcessor->run()
#8 C:\xampp\htdocs\framework\yii\framework\web\CBaseController.php(300): CBaseController->endWidget('CContentDecorat...')
#9 C:\xampp\htdocs\framework\yiiframework\protected\views\layouts\column1.php(6): CBaseController->endContent()
#10 C:\xampp\htdocs\framework\yii\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#11 C:\xampp\htdocs\framework\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#12 C:\xampp\htdocs\framework\yii\framework\web\CController.php(784): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#13 C:\xampp\htdocs\framework\yiiframework\protected\controllers\SiteController.php(32): CController->render('index')
#14 C:\xampp\htdocs\framework\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#15 C:\xampp\htdocs\framework\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#16 C:\xampp\htdocs\framework\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#17 C:\xampp\htdocs\framework\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 C:\xampp\htdocs\framework\yii\framework\web\CWebApplication.php(282): CController->run('index')
#19 C:\xampp\htdocs\framework\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/index')
#20 C:\xampp\htdocs\framework\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#21 C:\xampp\htdocs\framework\yiiframework\index.php(13): CApplication->run()
#22 {main}
REQUEST_URI=/framework/yiiframework/index.php/site/index
HTTP_REFERER=http://localhost/framework/yiiframework/index.php/site/login
---
2014/06/08 16:42:21 [error] [exception.CException] exception 'CException' with message 'Property "CWebUser.email" is not defined.' in C:\xampp\htdocs\framework\yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\framework\yii\framework\web\auth\CWebUser.php(146): CComponent->__get('email')
#1 C:\xampp\htdocs\framework\yiiframework\protected\views\layouts\main.php(37): CWebUser->__get('email')
#2 C:\xampp\htdocs\framework\yii\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#3 C:\xampp\htdocs\framework\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#4 C:\xampp\htdocs\framework\yii\framework\web\widgets\CContentDecorator.php(76): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#5 C:\xampp\htdocs\framework\yii\framework\web\widgets\CContentDecorator.php(54): CContentDecorator->decorate('<div id="conten...')
#6 C:\xampp\htdocs\framework\yii\framework\web\widgets\COutputProcessor.php(44): CContentDecorator->processOutput('<div id="conten...')
#7 C:\xampp\htdocs\framework\yii\framework\web\CBaseController.php(206): COutputProcessor->run()
#8 C:\xampp\htdocs\framework\yii\framework\web\CBaseController.php(300): CBaseController->endWidget('CContentDecorat...')
#9 C:\xampp\htdocs\framework\yiiframework\protected\views\layouts\column1.php(6): CBaseController->endContent()
#10 C:\xampp\htdocs\framework\yii\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#11 C:\xampp\htdocs\framework\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#12 C:\xampp\htdocs\framework\yii\framework\web\CController.php(784): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#13 C:\xampp\htdocs\framework\yiiframework\protected\controllers\SiteController.php(95): CController->render('login', Array)
#14 C:\xampp\htdocs\framework\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#15 C:\xampp\htdocs\framework\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#16 C:\xampp\htdocs\framework\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#17 C:\xampp\htdocs\framework\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 C:\xampp\htdocs\framework\yii\framework\web\CWebApplication.php(282): CController->run('login')
#19 C:\xampp\htdocs\framework\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#20 C:\xampp\htdocs\framework\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#21 C:\xampp\htdocs\framework\yiiframework\index.php(13): CApplication->run()
#22 {main}
REQUEST_URI=/framework/yiiframework/index.php/site/login
HTTP_REFERER=http://localhost/framework/yiiframework/index.php
---
2014/06/08 16:47:27 [error] [exception.CException] exception 'CException' with message 'Property "UserIdentity.setState" is not defined.' in C:\xampp\htdocs\framework\yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\framework\yiiframework\protected\components\UserIdentity.php(50): CComponent->__get('setState')
#1 C:\xampp\htdocs\framework\yiiframework\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#2 C:\xampp\htdocs\framework\yii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#3 C:\xampp\htdocs\framework\yii\framework\validators\CValidator.php(213): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#4 C:\xampp\htdocs\framework\yii\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#5 C:\xampp\htdocs\framework\yiiframework\protected\controllers\SiteController.php(84): CModel->validate()
#6 C:\xampp\htdocs\framework\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#7 C:\xampp\htdocs\framework\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 C:\xampp\htdocs\framework\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#9 C:\xampp\htdocs\framework\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\xampp\htdocs\framework\yii\framework\web\CWebApplication.php(282): CController->run('login')
#11 C:\xampp\htdocs\framework\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#12 C:\xampp\htdocs\framework\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#13 C:\xampp\htdocs\framework\yiiframework\index.php(13): CApplication->run()
#14 {main}
REQUEST_URI=/framework/yiiframework/index.php/site/login
HTTP_REFERER=http://localhost/framework/yiiframework/index.php/site/login
---
2014/06/08 16:48:21 [error] [exception.CException] exception 'CException' with message 'Property "CWebUser.username" is not defined.' in C:\xampp\htdocs\framework\yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\framework\yii\framework\web\auth\CWebUser.php(146): CComponent->__get('username')
#1 C:\xampp\htdocs\framework\yiiframework\protected\views\layouts\main.php(37): CWebUser->__get('username')
#2 C:\xampp\htdocs\framework\yii\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#3 C:\xampp\htdocs\framework\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#4 C:\xampp\htdocs\framework\yii\framework\web\widgets\CContentDecorator.php(76): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#5 C:\xampp\htdocs\framework\yii\framework\web\widgets\CContentDecorator.php(54): CContentDecorator->decorate('<div id="conten...')
#6 C:\xampp\htdocs\framework\yii\framework\web\widgets\COutputProcessor.php(44): CContentDecorator->processOutput('<div id="conten...')
#7 C:\xampp\htdocs\framework\yii\framework\web\CBaseController.php(206): COutputProcessor->run()
#8 C:\xampp\htdocs\framework\yii\framework\web\CBaseController.php(300): CBaseController->endWidget('CContentDecorat...')
#9 C:\xampp\htdocs\framework\yiiframework\protected\views\layouts\column1.php(6): CBaseController->endContent()
#10 C:\xampp\htdocs\framework\yii\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#11 C:\xampp\htdocs\framework\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#12 C:\xampp\htdocs\framework\yii\framework\web\CController.php(784): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#13 C:\xampp\htdocs\framework\yiiframework\protected\controllers\SiteController.php(30): CController->render('index')
#14 C:\xampp\htdocs\framework\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#15 C:\xampp\htdocs\framework\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#16 C:\xampp\htdocs\framework\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#17 C:\xampp\htdocs\framework\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 C:\xampp\htdocs\framework\yii\framework\web\CWebApplication.php(282): CController->run('index')
#19 C:\xampp\htdocs\framework\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/index')
#20 C:\xampp\htdocs\framework\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#21 C:\xampp\htdocs\framework\yiiframework\index.php(13): CApplication->run()
#22 {main}
REQUEST_URI=/framework/yiiframework/index.php/site/index
HTTP_REFERER=http://localhost/framework/yiiframework/index.php/site/login
---
